apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-05-26T13:26:10Z"
  creationTimestamp: "2023-05-26T13:25:50Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: garden-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 1.1.0
    helm.sh/chart: ingress-nginx-4.0.13
  name: garden-nginx-ingress-nginx-controller
  namespace: garden-system
  resourceVersion: "1295824"
  uid: 51887d3b-4182-402c-b19a-1b366a81e6d8
subsets:
- addresses:
  - ip: 10.1.15.139
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: garden-nginx-ingress-nginx-controller-wsb4w
      namespace: garden-system
      uid: 833d442d-381c-4804-99b3-a8addafc9f4f
  ports:
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
