apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-05-26T13:25:48Z"
  creationTimestamp: "2023-05-26T13:25:46Z"
  labels:
    module: default-backend
    service: default-backend
  name: default-backend
  namespace: garden-system
  resourceVersion: "1295758"
  uid: 68bae7ea-742e-400d-aef8-05d6e7fa52d4
subsets:
- addresses:
  - ip: 10.1.15.138
    nodeName: docker-desktop
    targetRef:
      kind: Pod
      name: default-backend-7d7d4b7b58-6z5lv
      namespace: garden-system
      uid: c374aa4c-ce03-4dea-b48d-00e1a2e0ce32
  ports:
  - name: http
    port: 80
    protocol: TCP
