apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-05-26T13:25:46Z"
deprecatedLastTimestamp: "2023-05-26T13:25:46Z"
deprecatedSource:
  component: replicaset-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-05-26T13:25:46Z"
  name: default-backend-7d7d4b7b58.1762b462b276c3a4
  namespace: garden-system
  resourceVersion: "1295741"
  uid: d11fd52d-3ef2-437d-be82-c7896cb83e75
note: 'Created pod: default-backend-7d7d4b7b58-6z5lv'
reason: SuccessfulCreate
regarding:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: default-backend-7d7d4b7b58
  namespace: garden-system
  resourceVersion: "1295736"
  uid: 0a0d5120-49fb-46fd-890b-904b42cd5c19
type: Normal
