apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-05-26T13:25:50Z"
involvedObject:
  apiVersion: apps/v1
  kind: DaemonSet
  name: garden-nginx-ingress-nginx-controller
  namespace: garden-system
  resourceVersion: "1295776"
  uid: e9d969fa-a097-4599-86b7-8198201e417d
kind: Event
lastTimestamp: "2023-05-26T13:25:50Z"
message: 'Created pod: garden-nginx-ingress-nginx-controller-wsb4w'
metadata:
  creationTimestamp: "2023-05-26T13:25:50Z"
  name: garden-nginx-ingress-nginx-controller.1762b46387da17f5
  namespace: garden-system
  resourceVersion: "1295780"
  uid: 1301cf17-8f99-4ccc-8021-711496df4be6
reason: SuccessfulCreate
reportingComponent: ""
reportingInstance: ""
source:
  component: daemonset-controller
type: Normal
