apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-05-26T13:25:47Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{default-backend}
  kind: Pod
  name: default-backend-7d7d4b7b58-6z5lv
  namespace: garden-system
  resourceVersion: "1295744"
  uid: c374aa4c-ce03-4dea-b48d-00e1a2e0ce32
kind: Event
lastTimestamp: "2023-05-26T13:25:47Z"
message: Created container default-backend
metadata:
  creationTimestamp: "2023-05-26T13:25:47Z"
  name: default-backend-7d7d4b7b58-6z5lv.1762b462e0942c14
  namespace: garden-system
  resourceVersion: "1295754"
  uid: d23b9dda-59d9-426d-9a69-405a9ce99219
reason: Created
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: docker-desktop
type: Normal
