apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: garden-nginx
    meta.helm.sh/release-namespace: garden-system
  creationTimestamp: "2023-05-26T13:25:50Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: garden-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 1.1.0
    helm.sh/chart: ingress-nginx-4.0.13
  name: garden-nginx-ingress-nginx
  namespace: garden-system
  resourceVersion: "1295766"
  uid: e682031e-bc6b-4f81-816d-20bccd87674a
