apiVersion: v1
kind: Pod
metadata:
  annotations:
    garden.io/generated: "true"
    garden.io/manifest-hash: e14e60d4361d65242c498b88ed26ce481592d6535d5c8102d20fef3f2ac0f0d5
    garden.io/version: v-2d58c28944
  creationTimestamp: "2023-05-26T13:57:52Z"
  generateName: default-backend-7d7d4b7b58-
  labels:
    module: default-backend
    pod-template-hash: 7d7d4b7b58
    service: default-backend
  name: default-backend-7d7d4b7b58-qz6vw
  namespace: garden-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: default-backend-7d7d4b7b58
    uid: 75f2bf1e-6bd2-4353-ae31-7187df7df8a1
  resourceVersion: "1298480"
  uid: 244c8729-9e2c-4303-a13a-9a26f5e98578
spec:
  containers:
  - env:
    - name: GARDEN_VERSION
      value: v-2d58c28944
    - name: GARDEN_MODULE_VERSION
      value: v-24864f339e
    - name: POD_HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: POD_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    image: gardendev/default-backend:v0.1
    imagePullPolicy: IfNotPresent
    name: default-backend
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 90Mi
    securityContext:
      allowPrivilegeEscalation: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-k75dr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 5
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-k75dr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-26T13:57:52Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-05-26T13:57:53Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-05-26T13:57:53Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-26T13:57:52Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://e2c3f0c076ac3f3a4588e19760249ba882ba5ef5e3c16a92aa7108243bc9fd50
    image: gardendev/default-backend:v0.1
    imageID: docker-pullable://gardendev/default-backend@sha256:1b02920425eea569c6be53bb2e3d2c1182243212de229be375da7a93594498cf
    lastState: {}
    name: default-backend
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-26T13:57:53Z"
  hostIP: 192.168.65.4
  phase: Running
  podIP: 10.1.15.140
  podIPs:
  - ip: 10.1.15.140
  qosClass: Burstable
  startTime: "2023-05-26T13:57:52Z"
