apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: garden-nginx
    meta.helm.sh/release-namespace: garden-system
  creationTimestamp: "2023-05-26T13:57:56Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: garden-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 1.1.0
    helm.sh/chart: ingress-nginx-4.0.13
  name: garden-nginx-ingress-nginx
  namespace: garden-system
  resourceVersion: "1298488"
  uid: 9c6db602-293f-48fe-b7d1-4caa62f7a256
