# 0.12.49
---
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
      garden.io/configured.replicas: "1"
      garden.io/generated: "true"
      garden.io/manifest-hash: 65a3c733dd05a34d3b8a8f0777a8379b3c5c81ec452ea27b3bddd4d7808f4746
      garden.io/version: v-cc30670b1e
    creationTimestamp: "2023-05-26T12:46:40Z"
    generation: 1
    labels:
      module: mysql
      pod-template-hash: 967df6654
      service: mysql
    name: mysql-967df6654
    namespace: localhost-demo
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: mysql
      uid: 6f76a460-6919-450e-add8-ba1b23295164
    resourceVersion: "1292511"
    uid: e4c455c9-4808-4af4-a2bc-145c2848e49c
  spec:
    replicas: 1
    selector:
      matchLabels:
        pod-template-hash: 967df6654
        service: mysql
    template:
      metadata:
        annotations:
          garden.io/generated: "true"
          garden.io/manifest-hash: c8e566c8d3af96d3b5103e9559719045329f8a8fab73fff1dbd20a4f7f4a7518
          garden.io/version: v-cc30670b1e
        creationTimestamp: null
        labels:
          module: mysql
          pod-template-hash: 967df6654
          service: mysql
      spec:
        containers:
        - env:
          - name: GARDEN_VERSION
            value: v-cc30670b1e
          - name: GARDEN_MODULE_VERSION
            value: v-b8ece8345c
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_USER
            value: demo
          - name: MYSQL_PASSWORD
            value: password
          - name: TZ
            value: America/New_York
          - name: POD_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: POD_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.serviceAccountName
          - name: POD_UID
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.uid
          image: mysql:8-debian
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - mysql
              - -u
              - root
              - --password=password
              - -e
              - SELECT 1
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          name: mysql
          ports:
          - containerPort: 3306
            name: mysql
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - mysql
              - -u
              - root
              - --password=password
              - -e
              - SELECT 1
            failureThreshold: 90
            initialDelaySeconds: 2
            periodSeconds: 1
            successThreshold: 2
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 90Mi
          securityContext:
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 5
        volumes:
        - emptyDir: {}
          name: mysql-volume
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
